//D&D 5e Default Weapons

//References to the ID numbers of the corresponding currency systems
const itemTypeId = 1; //Equipment
const subType = {
  simpleMelee: 1,
  simpleRanged: 2,
  martialMelee: 3,
  martialRanged: 4
};

module.exports.items = [
  {
    // id: 1,
    item_name: 'Club',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleMelee,
    value: 2,
    weight: 1,
    properties: "Light",
    //rangeLo: 0,
    //rangeHi: 0,
    //versatility: 0,
    damageType: 'bludgeoning',
    dice_type: 4,
    dice_count: 1
  },
  {
    // id: 2,
    item_name: 'Dagger',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleMelee,
    value: 2,
    weight: 2,
    properties: 'Finesse, light, thrown',
    rangeLo: 20,
    rangeHi: 60,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 4,
    dice_count: 1
  },
  {
    // id: 3,
    item_name: 'Greatclub',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleMelee,
    value: 0.2,
    weight: 10,
    properties: 'Two-handed',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'bludgeoning',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 4,
    item_name: 'Handaxe',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleMelee,
    value: 5,
    weight: 2,
    properties: 'Light, thrown',
    rangeLo: 20,
    rangeHi: 60,
    //versatility: 0,
    damageType: 'slashing',
    dice_type: 6,
    dice_count: 1
  },
  {
    // id: 5,
    item_name: 'Javelin',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleMelee,
    value: 0.2,
    weight: 2,
    properties: 'Thrown',
    rangeLo: 30,
    rangeHi: 120,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 6,
    dice_count: 1
  },
  {
    // id: 6,
    item_name: 'Light hammer',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleMelee,
    value: 2,
    weight: 2,
    properties: 'Light, thrown',
    rangeLo: 20,
    rangeHi: 60,
    //versatility: 0,
    damageType: 'bludgeoning',
    dice_type: 4,
    dice_count: 1
  },
  {
    // id: 7,
    item_name: 'Mace',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleMelee,
    value: 5,
    weight: 4,
    //properties: '',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'bludgeoning',
    dice_type: 6,
    dice_count: 1
  },
  {
    // id: 8,
    item_name: 'Quarterstaff',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleMelee,
    value: 0.2,
    weight: 4,
    properties: 'Versatile',
    // rangeLo: 0,
    // rangeHi: 0,
    versatility: 8,
    damageType: 'bludgeoning',
    dice_type: 6,
    dice_count: 1
  },
  {
    // id: 9,
    item_name: 'Sickle',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleMelee,
    value: 1,
    weight: 2,
    properties: 'Light',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'slashing',
    dice_type: 4,
    dice_count: 1
  },
  {
    // id: 10,
    item_name: 'Spear',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleMelee,
    value: 1,
    weight: 3,
    properties: 'Thrown, versatile',
    rangeLo: 20,
    rangeHi: 60,
    versatility: 8,
    damageType: 'piercing',
    dice_type: 6,
    dice_count: 1
  },
  {
    // id: 11,
    item_name: 'Crossbow, light',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleRanged,
    value: 25,
    weight: 5,
    properties: 'Ammunition, loading, two-handed',
    rangeLo: 80,
    rangeHi: 320,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 12,
    item_name: 'Dart',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleRanged,
    value: 0.05,
    weight: 0.25,
    properties: 'Finesse, thrown',
    rangeLo: 20,
    rangeHi: 60,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 4,
    dice_count: 1
  },
  {
    // id: 13,
    item_name: 'Shortbow',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleRanged,
    value: 25,
    weight: 2,
    properties: 'Ammunition, two-handed',
    rangeLo: 80,
    rangeHi: 320,
    //versatility: 0,
    damageType: '',
    dice_type: 6,
    dice_count: 1
  },
  {
    // id: 14,
    item_name: 'Sling',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.simpleRanged,
    value: 0.1,
    weight: 2,
    properties: 'Ammunition',
    rangeLo: 30,
    rangeHi: 120,
    //versatility: 0,
    damageType: 'bludgeoning',
    dice_type: 4,
    dice_count: 1
  },
  {
    // id: 15,
    item_name: 'Battleaxe',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 10,
    weight: 4,
    properties: 'Versatile',
    // rangeLo: 0,
    // rangeHi: 0,
    versatility: 10,
    damageType: 'slashing',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 16,
    item_name: 'Flail',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 10,
    weight: 2,
    // properties: '',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'bludgeoning',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 17,
    item_name: 'Glaive',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 20,
    weight: 6,
    properties: 'Heavy, reach, two-handed',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'slashing',
    dice_type: 10,
    dice_count: 1
  },
  {
    // id: 18,
    item_name: 'Greataxe',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 30,
    weight: 7,
    properties: 'Heavy, two-handed',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'slashing',
    dice_type: 12,
    dice_count: 1
  },
  {
    // id: 19,
    item_name: 'Greatsword',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 50,
    weight: 6,
    properties: 'Heavy, two-handed',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'slashing',
    dice_type: 6,
    dice_count: 2
  },
  {
    // id: 20,
    item_name: 'Halberd',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 20,
    weight: 6,
    properties: 'Heavy, reach, two-handed',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'slashing',
    dice_type: 10,
    dice_count: 1
  },
  {
    // id: 21,
    item_name: 'Lance',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 10,
    weight: 6,
    properties: 'Reach, special',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 12,
    dice_count: 1
  },
  {
    // id: 22,
    item_name: 'Longsword',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 15,
    weight: 3,
    properties: 'Versatile',
    // rangeLo: 0,
    // rangeHi: 0,
    versatility: 10,
    damageType: 'slashing',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 23,
    item_name: 'Maul',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 10,
    weight: 10,
    properties: 'Heavy, two-handed',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'bludgeoning',
    dice_type: 6,
    dice_count: 2
  },
  {
    // id: 24,
    item_name: 'Morningstar',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 15,
    weight: 2,
    // properties: '',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 25,
    item_name: 'Pike',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 5,
    weight: 18,
    properties: 'Heavy, reach, two-handed',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 10,
    dice_count: 1
  },
  {
    // id: 26,
    item_name: 'Rapier',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 25,
    weight: 2,
    properties: 'Finesse',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 27,
    item_name: 'Scimitar',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 25,
    weight: 3,
    properties: 'Finesse, light',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'slashing',
    dice_type: 6,
    dice_count: 1
  },
  {
    // id: 28,
    item_name: 'Shortsword',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 10,
    weight: 2,
    properties: 'Finesse, light',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'slashing',
    dice_type: 6,
    dice_count: 1
  },
  {
    // id: 29,
    item_name: 'Trident',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 5,
    weight: 4,
    properties: 'Thrown, versatile',
    rangeLo: 20,
    rangeHi: 60,
    versatility: 8,
    damageType: 'piercing',
    dice_type: 6,
    dice_count: 1
  },
  {
    // id: 30,
    item_name: 'War pick',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 5,
    weight: 2,
    // properties: '',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 31,
    item_name: 'Warhammer',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 15,
    weight: 2,
    properties: 'Versatile',
    // rangeLo: 0,
    // rangeHi: 0,
    versatility: 10,
    damageType: 'bludgeoning',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 32,
    item_name: 'Whip',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialMelee,
    value: 2,
    weight: 3,
    properties: 'Finesse, reach',
    // rangeLo: 0,
    // rangeHi: 0,
    //versatility: 0,
    damageType: 'slashing',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 33,
    item_name: 'Blowgun',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialRanged,
    value: 10,
    weight: 1,
    properties: 'Ammunition, loading',
    rangeLo: 25,
    rangeHi: 100,
    //versatility: 0,
    damageType: 'pircing',
    dice_type: 1,
    dice_count: 1
  },
  {
    // id: 34,
    item_name: 'Crossbow, hand',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialRanged,
    value: 75,
    weight: 3,
    properties: 'Ammunition, light, loading',
    rangeLo: 30,
    rangeHi: 120,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 6,
    dice_count: 1
  },
  {
    // id: 35,
    item_name: 'Crossbow, heavy',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialRanged,
    value: 50,
    weight: 18,
    properties: 'Ammunition, heavy, loading, two-handed',
    rangeLo: 100,
    rangeHi: 400,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 10,
    dice_count: 1
  },
  {
    // id: 36,
    item_name: 'Longbow',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialRanged,
    value: 50,
    weight: 2,
    properties: 'Ammunition, heavy, loading, two-handed',
    rangeLo: 150,
    rangeHi: 600,
    //versatility: 0,
    damageType: 'piercing',
    dice_type: 8,
    dice_count: 1
  },
  {
    // id: 37,
    item_name: 'Net',
    itemTypeId: itemTypeId,
    itemSubTypeId: subType.martialRanged,
    value: 1,
    weight: 3,
    properties: 'Special, thrown',
    rangeLo: 5,
    rangeHi: 15,
    //versatility: 0,
    // damageType: '',
    // dice_type: 0,
    // dice_count: 0
  },
];