//Sample data that could otherwise only be generated by user activity

module.exports.users = [
  {
    // id: 1,
    user_name: 'admin',
    user_email: 'admin@magecase.com',
    password: 'REDACTED',
    premium_status: true,
    user_icon: 'www.url_to_icon1.net',
    char_count: 2,
    game_count: 1
  },
  {
    // id: 2
    user_name: 'nihilates',
    user_email: 'nihilates@gmail.com',
    password: 'password123',
    premium_status: false,
    user_icon: 'www.url_to_icon2.net',
    char_count: 0,
    game_count: 0
  }
];

module.exports.games = [
  {
    game_name: 'Fantasy Texas',
    userId: 1,
    currencyId: 1
  }
];

module.exports.characters = [
  {
    char_name: 'Biff Meatwagon',
    userId: 1,
    gameId: 1,
    currencyId: 1
  }
];