//Sample data that could otherwise only be generated by user activity

module.exports.users = [
  {
    // id: 1,
    user_name: 'admin',
    user_email: 'admin@magecase.com',
    password: 'REDACTED',
    premium_status: true,
    user_icon: 'www.url_to_icon1.net',
    char_count: 2,
    game_count: 1
  },
  {
    // id: 2
    user_name: 'nihilates',
    user_email: 'nihilates@gmail.com',
    password: 'password123',
    premium_status: false,
    user_icon: 'www.url_to_icon2.net',
    char_count: 0,
    game_count: 0
  }
];

module.exports.games = [
  {
    // id: 1,
    game_name: 'Fantasy Texas',
    userId: 1,
    currencySystemId: 1
  },
  {
    // id: 2,
    game_name: 'Tim\'s Campaign',
    userId: 1,
    currencySystemId: 1
  },
  {
    // id: 3,
    game_name: 'Innistrad',
    userId: 2,
    currencySystemId: 1
  },
  {
    id: 4,
    game_name: 'Laser Dragons',
    userId: 2,
    currencySystemId: 1
  }
];

module.exports.characters = [
  {
    char_name: 'Biff Meatwagon',
    userId: 1,
    gameId: 1,
    currencySystemId: 1
  },
  {
    char_name: 'Sinjun',
    userId: 2,
    gameId: 3,
    currencySystemId: 1,
  },
  {
    char_name: 'Dash Manly',
    userId: 2,
    gameId: 2,
    currencySystemId: 1,
  },
  {
    char_name: 'Rick Rimshot',
    userId: 1,
    gameId: 2,
    currencySystemId: 1,
  }
];

module.exports.currencySystems = [
  {
    // id: 3, //starts at 3 because there are already 2 non-custom systems
    system_name: 'Innistrad',
    is_custom: true,
    userId: 2, //user ID for "nihilates" account
  }
];

module.exports.currencyUnits = [
  {
  // id: 6, //starts at 6 because there already exist several currencies on the table
    unit_name: 'Pence',
    unit_value: 0.01,
    currencySystemId: 3, //these belong to the Innistrad system
  },
  {
  // id: 7,
    unit_name: 'Mark',
    unit_value: 0.1,
    currencySystemId: 3,
  },
  {
  // id: 8,
    unit_name: 'Sovereign',
    unit_value: 1,
    currencySystemId: 3,
  },
];

module.exports.inventories = [
  //Sinjun's Inventory
  {
    charId: 2,
    itemId: 26, //Rapier
    count: 1
  },
  {
    charId: 2,
    itemId: 2, //Dagger
    count: 2
  },
  {
    charId: 2,
    itemId: 13, //Shortbow
    count: 1
  }
  //End of Sinjun's Inventory
];

const shop = { //Shop type key
  weapons: 1,
  armors: 2,
  apothecary: 3,
  adventurGear: 4,
  magics: 5
};

module.exports.shops = [
  {
    //id: 1,
    shop_name: 'Aelyndar\'s Emporeum',
    typeId: shop.magics,
    userId: 2,
    gameId: 2
  },
  {
    //id: 2,
    shop_name: 'Reilad\'s Hammer',
    typeId: shop.weapons,
    userId: 2,
    gameId: 2
  },
  {
    //id: 3,
    shop_name: 'Poisons by Sneakers',
    typeId: shop.apothecary,
    userId: 2,
    gameId: 2
  }
];
//1,3,6,7,16,23,31
module.exports.shopInventories = [
  {
    shopId: 2, //Reilad's Hammer
    currencySystemId: 1,
    itemId: 1, //Club
    count: 5
  },
  {
    shopId: 2, //Reilad's Hammer
    currencySystemId: 1,
    itemId: 3, //Greatclub
    count: 8
  },
  {
    shopId: 2, //Reilad's Hammer
    currencySystemId: 1,
    itemId: 6, //Light hammer
    count: 9
  },
  {
    shopId: 2, //Reilad's Hammer
    currencySystemId: 1,
    itemId: 7, //Mace
    count: 3
  },
  {
    shopId: 2, //Reilad's Hammer
    currencySystemId: 1,
    itemId: 16, //Flail
    count: 4
  },
  {
    shopId: 2, //Reilad's Hammer
    currencySystemId: 1,
    itemId: 23, //Maul
    count: 2
  },
  {
    shopId: 2, //Reilad's Hammer
    currencySystemId: 1,
    itemId: 31, //Warhammer
    count: 3
  }
];